# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ring_oscillator/ring_oscillator.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ring_oscillator || ORIG_REF_NAME==ring_oscillator} -quiet] -quiet

# IP: bd/ring_oscillator/ip/ring_oscillator_util_vector_logic_0_0/ring_oscillator_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ring_oscillator_util_vector_logic_0_0 || ORIG_REF_NAME==ring_oscillator_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ring_oscillator/ip/ring_oscillator_util_vector_logic_0_2/ring_oscillator_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ring_oscillator_util_vector_logic_0_2 || ORIG_REF_NAME==ring_oscillator_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/ring_oscillator/ip/ring_oscillator_util_vector_logic_0_3/ring_oscillator_util_vector_logic_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ring_oscillator_util_vector_logic_0_3 || ORIG_REF_NAME==ring_oscillator_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/ring_oscillator/ip/ring_oscillator_util_vector_logic_2_0/ring_oscillator_util_vector_logic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ring_oscillator_util_vector_logic_2_0 || ORIG_REF_NAME==ring_oscillator_util_vector_logic_2_0} -quiet] -quiet

# XDC: e:/Vivado/PUF_Project/Ring_Oscillator/Ring_Oscillator.gen/sources_1/bd/ring_oscillator/ring_oscillator_ooc.xdc
