# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/ring_oscillator_16/ring_oscillator_16.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ring_oscillator_16 || ORIG_REF_NAME==ring_oscillator_16} -quiet] -quiet

# Block Designs: bd/final_assembly/final_assembly.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly || ORIG_REF_NAME==final_assembly} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_xlconcat_0_0/final_assembly_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_xlconcat_0_0 || ORIG_REF_NAME==final_assembly_xlconcat_0_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_xlconcat_1_0/final_assembly_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_xlconcat_1_0 || ORIG_REF_NAME==final_assembly_xlconcat_1_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_c_counter_binary_0_0/final_assembly_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_c_counter_binary_0_0 || ORIG_REF_NAME==final_assembly_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_c_counter_binary_1_0/final_assembly_c_counter_binary_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_c_counter_binary_1_0 || ORIG_REF_NAME==final_assembly_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_xlslice_0_0/final_assembly_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_xlslice_0_0 || ORIG_REF_NAME==final_assembly_xlslice_0_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_xlslice_1_0/final_assembly_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_xlslice_1_0 || ORIG_REF_NAME==final_assembly_xlslice_1_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_multiplexer_16to1_0_0/final_assembly_multiplexer_16to1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_multiplexer_16to1_0_0 || ORIG_REF_NAME==final_assembly_multiplexer_16to1_0_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_multiplexer_16to1_1_0/final_assembly_multiplexer_16to1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_multiplexer_16to1_1_0 || ORIG_REF_NAME==final_assembly_multiplexer_16to1_1_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_comparator_0_0/final_assembly_comparator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_comparator_0_0 || ORIG_REF_NAME==final_assembly_comparator_0_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_ring_oscillator_16_w_0_0/final_assembly_ring_oscillator_16_w_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_ring_oscillator_16_w_0_0 || ORIG_REF_NAME==final_assembly_ring_oscillator_16_w_0_0} -quiet] -quiet

# Block Designs: bd/ring_oscillator_16/ring_oscillator_16.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ring_oscillator_16 || ORIG_REF_NAME==ring_oscillator_16} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_ring_oscillator_16_w_1_0/final_assembly_ring_oscillator_16_w_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_ring_oscillator_16_w_1_0 || ORIG_REF_NAME==final_assembly_ring_oscillator_16_w_1_0} -quiet] -quiet

# Block Designs: bd/ring_oscillator_16/ring_oscillator_16.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ring_oscillator_16 || ORIG_REF_NAME==ring_oscillator_16} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_Accumulator_0_0/final_assembly_Accumulator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_Accumulator_0_0 || ORIG_REF_NAME==final_assembly_Accumulator_0_0} -quiet] -quiet

# IP: bd/final_assembly/ip/final_assembly_xlconstant_0_0/final_assembly_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_assembly_xlconstant_0_0 || ORIG_REF_NAME==final_assembly_xlconstant_0_0} -quiet] -quiet

# XDC: f:/Vivado/PUF_Project/Ring_oscillator_PUF/Ring_oscillator_PUF.gen/sources_1/bd/ring_oscillator_16/ring_oscillator_16_ooc.xdc

# XDC: f:/Vivado/PUF_Project/Ring_oscillator_PUF/Ring_oscillator_PUF.gen/sources_1/bd/ring_oscillator_16/ring_oscillator_16_ooc.xdc

# XDC: f:/Vivado/PUF_Project/Ring_oscillator_PUF/Ring_oscillator_PUF.gen/sources_1/bd/ring_oscillator_16/ring_oscillator_16_ooc.xdc

# XDC: f:/Vivado/PUF_Project/Ring_oscillator_PUF/Ring_oscillator_PUF.gen/sources_1/bd/final_assembly/final_assembly_ooc.xdc
