@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Apr 12 14:29:53 +0530 2024
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim final_assembly_wrapper_time_synth -key {Post-Synthesis:sim_1:Timing:final_assembly_wrapper} -tclbatch final_assembly_wrapper.tcl -protoinst "protoinst_files/ring_oscillator_16.protoinst" -protoinst "protoinst_files/final_assembly.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_2.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_3.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_4.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_5.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_6.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_7.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_8.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_9.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_10.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_11.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_12.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_13.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_14.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_15.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_16.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_17.protoinst" -view C:/PUF_Project/PUF_Project/Ring_oscillator_PUF/ring_oscillator_wrapper_time_synth.wcfg -log simulate.log"
call xsim  final_assembly_wrapper_time_synth -key {Post-Synthesis:sim_1:Timing:final_assembly_wrapper} -tclbatch final_assembly_wrapper.tcl -protoinst "protoinst_files/ring_oscillator_16.protoinst" -protoinst "protoinst_files/final_assembly.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_2.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_3.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_4.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_5.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_6.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_7.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_8.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_9.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_10.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_11.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_12.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_13.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_14.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_15.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_16.protoinst" -protoinst "protoinst_files/ring_oscillator_inst_17.protoinst" -view C:/PUF_Project/PUF_Project/Ring_oscillator_PUF/ring_oscillator_wrapper_time_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
